name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

permissions:
  contents: read

jobs:
  test:
    name: Test & Build
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [20.x]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Compile contracts
        run: npx hardhat compile

      - name: Run tests
        run: npx hardhat test

      - name: Run coverage
        run: npx hardhat coverage
        continue-on-error: true

      - name: Generate gas report
        run: npx hardhat test
        env:
          GAS_REPORT: true
        continue-on-error: true

      - name: Upload gas report
        uses: actions/upload-artifact@v4
        if: success()
        with:
          name: gas-report
          path: |
            gas-report.txt
            gasReporterOutput.json
          retention-days: 30

      - name: Upload coverage
        uses: actions/upload-artifact@v4
        if: success()
        with:
          name: coverage
          path: coverage/
          retention-days: 30

  lint:
    name: Lint
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run Solidity linter
        run: npm run lint
        continue-on-error: true

      - name: Check formatting
        run: npm run format:check
        continue-on-error: true

  security:
    name: Security Analysis
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Compile contracts
        run: npx hardhat compile

      - name: Run Slither (if available)
        run: |
          if command -v slither &> /dev/null; then
            slither . --filter-paths "node_modules|test" || true
          else
            echo "Slither not installed, skipping"
          fi
        continue-on-error: true

  build-summary:
    name: Build Summary
    runs-on: ubuntu-latest
    needs: [test, lint]
    if: always()
    
    steps:
      - name: Check test result
        if: needs.test.result != 'success'
        run: exit 1
      
      - name: Success message
        if: needs.test.result == 'success'
        run: echo "✅ All tests passed successfully"

